# 使用官方 PyTorch 镜像作为基础镜像
FROM docker.io/pytorch/pytorch:2.4.0-cuda12.1-cudnn9-devel

# 复制本地文件到容器的工作目录
COPY . /data/my_module_base

# 设置工作目录
WORKDIR /workspace

# 定义环境变量
ENV CUDA_VISIBLE_DEVICES=0,1

# 安装依赖
RUN pip install -r /data/my_module_base/requirements_all.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
# RUN pip uninstall torch
# RUN pip install pip install torch-2.4.0+cu121-cp311-cp311-linux_x86_64.whl -i https://pypi.tuna.tsinghua.edu.cn/simple
# RUN pip install torchaudio-2.4.0+cu121-cp311-cp311-linux_x86_64.whl -i https://pypi.tuna.tsinghua.edu.cn/simple
# RUN pip install torchvision-0.19.0+cu121-cp311-cp311-linux_x86_64.whl -i https://pypi.tuna.tsinghua.edu.cn/simple

# 暴露应用运行的端口
EXPOSE 8080